Contribution with a 1D magnetotelluric example
inlab-geo/espresso pull request #100
Opened 2023-02-01 09:47 UTC by hseille

I have added a 1D magnetotelluric problem. I tried to follow the template as much as possible.  
I built it with cofi-espresso, it worked.
I also prepared some examples to run within jupyter notebooks, they are not included here, I will include them to the cofi-examples later I guess?

Cheers,
Hoel

2023-02-01 12:31 UTC, valentineap commented
Thanks for this, @hseille - congratulations on being our first external contributor!

I think you've already discussed this with @jwhhh so I'll let her deal with the pull request. 

We haven't yet fully decided how we manage and serve things like Jupyter notebooks. We probably want to automagically link these into the [documentation](https://cofi-espresso.readthedocs.io), but @jwhhh and I need to think about how we do this in a standardised way. It would be very useful to have access to your notebooks so that we can experiment with different solutions -- perhaps you could create a folder `contrib/magnetotelluric_1d/examples` or similar and add them there for now. We can move them later if needed.

Thanks again for spending your time on this - and if you have any comments/suggestions about the contribution process/instructions/etc we'd love to hear them!

2023-02-01 23:13 UTC, jwhhh requested changes
Thank you for being our first external contributor! The example looks all good and passes all tests. It would be great if you could add some text to introduce what the problem is about (as is also mentioned in a separate comment under `README.md`). 

And if you have notebooks to include, that's great! Please include your notebook(s) under a "contrib/magnetotelluric/examples" folder, and we'll try to update our infrastructure so that your example notebook will be displayed in the documentation.

Thanks again for the contribution!

2023-02-01 23:13 UTC, jwhhh commented on contrib/magnetotelluric_1D/README.md
> +<!-- Please write anything you'd like to explain about the forward problem here -->
Hello Hoel, would you like to document briefly what the problem is about, how to use it (if there's anything special and additional to the "standard" interface), and anything else you think would be beneficial to explain? This document is in Markdown format, so you can write titles starting with `#` (`##` for header 2 and so on) and normal paragraphs with empty lines in between, etc. And please remove all the currently existing content after that.

2023-02-02 09:50 UTC, jwhhh approved these changes

2023-03-06 01:11 UTC, merged